# Generated by Django 4.2.5 on 2023-09-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traniee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrnme', models.CharField(max_length=20)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60)),
                ('track', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=8)),
            ],
        ),
    ]
