# Generated by Django 4.2.5 on 2023-09-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_track_trainee_delete_traniee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='track',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
